-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#252236", bg = "#c4a4fd", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2e2c40" }, c = { fg = "#7c869c", bg = "#1f1c2f" } },
  insert = { a = { fg = "#252236", bg = "#85cc87", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2e2c40" }, c = { fg = "#7c869c", bg = "#1f1c2f" } },
  visual = { a = { fg = "#252236", bg = "#b6aaff", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2e2c40" }, c = { fg = "#7c869c", bg = "#1f1c2f" } },
  replace = { a = { fg = "#252236", bg = "#fb9795", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2e2c40" }, c = { fg = "#7c869c", bg = "#1f1c2f" } },
  command = { a = { fg = "#252236", bg = "#dbb155", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2e2c40" }, c = { fg = "#7c869c", bg = "#1f1c2f" } },
  inactive = { a = { fg = "#7c869c", bg = "#1f1c2f" }, b = { fg = "#7c869c", bg = "#1f1c2f" }, c = { fg = "#7c869c", bg = "#1f1c2f" } },
}
