-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#13111c", bg = "#c9acff", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1c1a26" }, c = { fg = "#b2b8c1", bg = "#0e0b17" } },
  insert = { a = { fg = "#13111c", bg = "#76e87d", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1c1a26" }, c = { fg = "#b2b8c1", bg = "#0e0b17" } },
  visual = { a = { fg = "#13111c", bg = "#b0b7ff", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1c1a26" }, c = { fg = "#b2b8c1", bg = "#0e0b17" } },
  replace = { a = { fg = "#13111c", bg = "#fe7f78", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1c1a26" }, c = { fg = "#b2b8c1", bg = "#0e0b17" } },
  command = { a = { fg = "#13111c", bg = "#f6d653", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1c1a26" }, c = { fg = "#b2b8c1", bg = "#0e0b17" } },
  inactive = { a = { fg = "#b2b8c1", bg = "#0e0b17" }, b = { fg = "#b2b8c1", bg = "#0e0b17" }, c = { fg = "#b2b8c1", bg = "#0e0b17" } },
}
