-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#301e2c", bg = "#fe9783", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#3b2836" }, c = { fg = "#828ca2", bg = "#2a1926" } },
  insert = { a = { fg = "#301e2c", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#3b2836" }, c = { fg = "#828ca2", bg = "#2a1926" } },
  visual = { a = { fg = "#301e2c", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#3b2836" }, c = { fg = "#828ca2", bg = "#2a1926" } },
  replace = { a = { fg = "#301e2c", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#3b2836" }, c = { fg = "#828ca2", bg = "#2a1926" } },
  command = { a = { fg = "#301e2c", bg = "#e7c454", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#3b2836" }, c = { fg = "#828ca2", bg = "#2a1926" } },
  inactive = { a = { fg = "#828ca2", bg = "#2a1926" }, b = { fg = "#828ca2", bg = "#2a1926" }, c = { fg = "#828ca2", bg = "#2a1926" } },
}
