-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#26263a", bg = "#c4a4fd", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#302f45" }, c = { fg = "#828ca2", bg = "#202034" } },
  insert = { a = { fg = "#26263a", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#302f45" }, c = { fg = "#828ca2", bg = "#202034" } },
  visual = { a = { fg = "#26263a", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#302f45" }, c = { fg = "#828ca2", bg = "#202034" } },
  replace = { a = { fg = "#26263a", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#302f45" }, c = { fg = "#828ca2", bg = "#202034" } },
  command = { a = { fg = "#26263a", bg = "#e7be62", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#302f45" }, c = { fg = "#828ca2", bg = "#202034" } },
  inactive = { a = { fg = "#828ca2", bg = "#202034" }, b = { fg = "#828ca2", bg = "#202034" }, c = { fg = "#828ca2", bg = "#202034" } },
}
