-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#282134", bg = "#e198ec", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#322b3f" }, c = { fg = "#828ca2", bg = "#221b2e" } },
  insert = { a = { fg = "#282134", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#322b3f" }, c = { fg = "#828ca2", bg = "#221b2e" } },
  visual = { a = { fg = "#282134", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#322b3f" }, c = { fg = "#828ca2", bg = "#221b2e" } },
  replace = { a = { fg = "#282134", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#322b3f" }, c = { fg = "#828ca2", bg = "#221b2e" } },
  command = { a = { fg = "#282134", bg = "#e7c454", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#322b3f" }, c = { fg = "#828ca2", bg = "#221b2e" } },
  inactive = { a = { fg = "#828ca2", bg = "#221b2e" }, b = { fg = "#828ca2", bg = "#221b2e" }, c = { fg = "#828ca2", bg = "#221b2e" } },
}
