-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#f6f3ed", bg = "#2e69b2", gui = "bold" }, b = { fg = "#535864", bg = "#e9e6e0" }, c = { fg = "#747a87", bg = "#eeebe5" } },
  insert = { a = { fg = "#f6f3ed", bg = "#2e7c35", gui = "bold" }, b = { fg = "#535864", bg = "#e9e6e0" }, c = { fg = "#747a87", bg = "#eeebe5" } },
  visual = { a = { fg = "#f6f3ed", bg = "#6959ae", gui = "bold" }, b = { fg = "#535864", bg = "#e9e6e0" }, c = { fg = "#747a87", bg = "#eeebe5" } },
  replace = { a = { fg = "#f6f3ed", bg = "#a74546", gui = "bold" }, b = { fg = "#535864", bg = "#e9e6e0" }, c = { fg = "#747a87", bg = "#eeebe5" } },
  command = { a = { fg = "#f6f3ed", bg = "#856302", gui = "bold" }, b = { fg = "#535864", bg = "#e9e6e0" }, c = { fg = "#747a87", bg = "#eeebe5" } },
  inactive = { a = { fg = "#747a87", bg = "#eeebe5" }, b = { fg = "#747a87", bg = "#eeebe5" }, c = { fg = "#747a87", bg = "#eeebe5" } },
}
