-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#faf2e8", bg = "#2e69b2", gui = "bold" }, b = { fg = "#535864", bg = "#ede5db" }, c = { fg = "#747a87", bg = "#f2eae0" } },
  insert = { a = { fg = "#faf2e8", bg = "#2e7c35", gui = "bold" }, b = { fg = "#535864", bg = "#ede5db" }, c = { fg = "#747a87", bg = "#f2eae0" } },
  visual = { a = { fg = "#faf2e8", bg = "#6959ae", gui = "bold" }, b = { fg = "#535864", bg = "#ede5db" }, c = { fg = "#747a87", bg = "#f2eae0" } },
  replace = { a = { fg = "#faf2e8", bg = "#a74546", gui = "bold" }, b = { fg = "#535864", bg = "#ede5db" }, c = { fg = "#747a87", bg = "#f2eae0" } },
  command = { a = { fg = "#faf2e8", bg = "#856302", gui = "bold" }, b = { fg = "#535864", bg = "#ede5db" }, c = { fg = "#747a87", bg = "#f2eae0" } },
  inactive = { a = { fg = "#747a87", bg = "#f2eae0" }, b = { fg = "#747a87", bg = "#f2eae0" }, c = { fg = "#747a87", bg = "#f2eae0" } },
}
