-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#252236", bg = "#c4a4fd", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e2c40" }, c = { fg = "#828ca2", bg = "#1f1c2f" } },
  insert = { a = { fg = "#252236", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e2c40" }, c = { fg = "#828ca2", bg = "#1f1c2f" } },
  visual = { a = { fg = "#252236", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e2c40" }, c = { fg = "#828ca2", bg = "#1f1c2f" } },
  replace = { a = { fg = "#252236", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e2c40" }, c = { fg = "#828ca2", bg = "#1f1c2f" } },
  command = { a = { fg = "#252236", bg = "#e7c454", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e2c40" }, c = { fg = "#828ca2", bg = "#1f1c2f" } },
  inactive = { a = { fg = "#828ca2", bg = "#1f1c2f" }, b = { fg = "#828ca2", bg = "#1f1c2f" }, c = { fg = "#828ca2", bg = "#1f1c2f" } },
}
