-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#1a0e16", bg = "#fda290", gui = "bold" }, b = { fg = "#cbd1da", bg = "#231720" }, c = { fg = "#b2b8c1", bg = "#140911" } },
  insert = { a = { fg = "#1a0e16", bg = "#76e87d", gui = "bold" }, b = { fg = "#cbd1da", bg = "#231720" }, c = { fg = "#b2b8c1", bg = "#140911" } },
  visual = { a = { fg = "#1a0e16", bg = "#b1b7fd", gui = "bold" }, b = { fg = "#cbd1da", bg = "#231720" }, c = { fg = "#b2b8c1", bg = "#140911" } },
  replace = { a = { fg = "#1a0e16", bg = "#fe7f78", gui = "bold" }, b = { fg = "#cbd1da", bg = "#231720" }, c = { fg = "#b2b8c1", bg = "#140911" } },
  command = { a = { fg = "#1a0e16", bg = "#f6d653", gui = "bold" }, b = { fg = "#cbd1da", bg = "#231720" }, c = { fg = "#b2b8c1", bg = "#140911" } },
  inactive = { a = { fg = "#b2b8c1", bg = "#140911" }, b = { fg = "#b2b8c1", bg = "#140911" }, c = { fg = "#b2b8c1", bg = "#140911" } },
}
