-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#191a20", bg = "#a9cefd", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#22242a" }, c = { fg = "#b2b8c2", bg = "#13151a" } },
  insert = { a = { fg = "#191a20", bg = "#88e48c", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#22242a" }, c = { fg = "#b2b8c2", bg = "#13151a" } },
  visual = { a = { fg = "#191a20", bg = "#c9c2fd", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#22242a" }, c = { fg = "#b2b8c2", bg = "#13151a" } },
  replace = { a = { fg = "#191a20", bg = "#feb5b1", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#22242a" }, c = { fg = "#b2b8c2", bg = "#13151a" } },
  command = { a = { fg = "#191a20", bg = "#f7c243", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#22242a" }, c = { fg = "#b2b8c2", bg = "#13151a" } },
  inactive = { a = { fg = "#b2b8c2", bg = "#13151a" }, b = { fg = "#b2b8c2", bg = "#13151a" }, c = { fg = "#b2b8c2", bg = "#13151a" } },
}
