-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#23242e", bg = "#86bafe", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2e38" }, c = { fg = "#7c869c", bg = "#1d1f28" } },
  insert = { a = { fg = "#23242e", bg = "#85cc87", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2e38" }, c = { fg = "#7c869c", bg = "#1d1f28" } },
  visual = { a = { fg = "#23242e", bg = "#b6aaff", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2e38" }, c = { fg = "#7c869c", bg = "#1d1f28" } },
  replace = { a = { fg = "#23242e", bg = "#fb9795", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2e38" }, c = { fg = "#7c869c", bg = "#1d1f28" } },
  command = { a = { fg = "#23242e", bg = "#dbb155", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2e38" }, c = { fg = "#7c869c", bg = "#1d1f28" } },
  inactive = { a = { fg = "#7c869c", bg = "#1d1f28" }, b = { fg = "#7c869c", bg = "#1d1f28" }, c = { fg = "#7c869c", bg = "#1d1f28" } },
}
