-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#27253a", bg = "#e198ec", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f44" }, c = { fg = "#828ca2", bg = "#211f34" } },
  insert = { a = { fg = "#27253a", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f44" }, c = { fg = "#828ca2", bg = "#211f34" } },
  visual = { a = { fg = "#27253a", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f44" }, c = { fg = "#828ca2", bg = "#211f34" } },
  replace = { a = { fg = "#27253a", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f44" }, c = { fg = "#828ca2", bg = "#211f34" } },
  command = { a = { fg = "#27253a", bg = "#e7be62", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f44" }, c = { fg = "#828ca2", bg = "#211f34" } },
  inactive = { a = { fg = "#828ca2", bg = "#211f34" }, b = { fg = "#828ca2", bg = "#211f34" }, c = { fg = "#828ca2", bg = "#211f34" } },
}
