-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#0a0f22", bg = "#83b4f3", gui = "bold" }, b = { fg = "#8f98ab", bg = "#13182c" }, c = { fg = "#6c7587", bg = "#06091c" } },
  insert = { a = { fg = "#0a0f22", bg = "#86c387", gui = "bold" }, b = { fg = "#8f98ab", bg = "#13182c" }, c = { fg = "#6c7587", bg = "#06091c" } },
  visual = { a = { fg = "#0a0f22", bg = "#b0a6ef", gui = "bold" }, b = { fg = "#8f98ab", bg = "#13182c" }, c = { fg = "#6c7587", bg = "#06091c" } },
  replace = { a = { fg = "#0a0f22", bg = "#ec9693", gui = "bold" }, b = { fg = "#8f98ab", bg = "#13182c" }, c = { fg = "#6c7587", bg = "#06091c" } },
  command = { a = { fg = "#0a0f22", bg = "#d0ac5f", gui = "bold" }, b = { fg = "#8f98ab", bg = "#13182c" }, c = { fg = "#6c7587", bg = "#06091c" } },
  inactive = { a = { fg = "#6c7587", bg = "#06091c" }, b = { fg = "#6c7587", bg = "#06091c" }, c = { fg = "#6c7587", bg = "#06091c" } },
}
