-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#1a2637", bg = "#58c4fd", gui = "bold" }, b = { fg = "#a0abc2", bg = "#233041" }, c = { fg = "#7c869c", bg = "#142030" } },
  insert = { a = { fg = "#1a2637", bg = "#85cc87", gui = "bold" }, b = { fg = "#a0abc2", bg = "#233041" }, c = { fg = "#7c869c", bg = "#142030" } },
  visual = { a = { fg = "#1a2637", bg = "#b6aaff", gui = "bold" }, b = { fg = "#a0abc2", bg = "#233041" }, c = { fg = "#7c869c", bg = "#142030" } },
  replace = { a = { fg = "#1a2637", bg = "#fb9795", gui = "bold" }, b = { fg = "#a0abc2", bg = "#233041" }, c = { fg = "#7c869c", bg = "#142030" } },
  command = { a = { fg = "#1a2637", bg = "#dbb155", gui = "bold" }, b = { fg = "#a0abc2", bg = "#233041" }, c = { fg = "#7c869c", bg = "#142030" } },
  inactive = { a = { fg = "#7c869c", bg = "#142030" }, b = { fg = "#7c869c", bg = "#142030" }, c = { fg = "#7c869c", bg = "#142030" } },
}
