-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#161a26", bg = "#a9cefd", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#1f2430" }, c = { fg = "#b2b8c2", bg = "#111420" } },
  insert = { a = { fg = "#161a26", bg = "#88e48c", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#1f2430" }, c = { fg = "#b2b8c2", bg = "#111420" } },
  visual = { a = { fg = "#161a26", bg = "#c9c2fd", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#1f2430" }, c = { fg = "#b2b8c2", bg = "#111420" } },
  replace = { a = { fg = "#161a26", bg = "#feb5b1", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#1f2430" }, c = { fg = "#b2b8c2", bg = "#111420" } },
  command = { a = { fg = "#161a26", bg = "#f7c243", gui = "bold" }, b = { fg = "#cbd1dc", bg = "#1f2430" }, c = { fg = "#b2b8c2", bg = "#111420" } },
  inactive = { a = { fg = "#b2b8c2", bg = "#111420" }, b = { fg = "#b2b8c2", bg = "#111420" }, c = { fg = "#b2b8c2", bg = "#111420" } },
}
