-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#f9fafc", bg = "#2769b7", gui = "bold" }, b = { fg = "#484d58", bg = "#ebedef" }, c = { fg = "#696f7b", bg = "#f0f2f4" } },
  insert = { a = { fg = "#f9fafc", bg = "#267d30", gui = "bold" }, b = { fg = "#484d58", bg = "#ebedef" }, c = { fg = "#696f7b", bg = "#f0f2f4" } },
  visual = { a = { fg = "#f9fafc", bg = "#6a57b3", gui = "bold" }, b = { fg = "#484d58", bg = "#ebedef" }, c = { fg = "#696f7b", bg = "#f0f2f4" } },
  replace = { a = { fg = "#f9fafc", bg = "#ab4043", gui = "bold" }, b = { fg = "#484d58", bg = "#ebedef" }, c = { fg = "#696f7b", bg = "#f0f2f4" } },
  command = { a = { fg = "#f9fafc", bg = "#846308", gui = "bold" }, b = { fg = "#484d58", bg = "#ebedef" }, c = { fg = "#696f7b", bg = "#f0f2f4" } },
  inactive = { a = { fg = "#696f7b", bg = "#f0f2f4" }, b = { fg = "#696f7b", bg = "#f0f2f4" }, c = { fg = "#696f7b", bg = "#f0f2f4" } },
}
