-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#15101b", bg = "#f095ff", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1e1925" }, c = { fg = "#b2b8c1", bg = "#0f0b16" } },
  insert = { a = { fg = "#15101b", bg = "#76e87d", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1e1925" }, c = { fg = "#b2b8c1", bg = "#0f0b16" } },
  visual = { a = { fg = "#15101b", bg = "#b1b7fd", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1e1925" }, c = { fg = "#b2b8c1", bg = "#0f0b16" } },
  replace = { a = { fg = "#15101b", bg = "#fe7f78", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1e1925" }, c = { fg = "#b2b8c1", bg = "#0f0b16" } },
  command = { a = { fg = "#15101b", bg = "#f6d653", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1e1925" }, c = { fg = "#b2b8c1", bg = "#0f0b16" } },
  inactive = { a = { fg = "#b2b8c1", bg = "#0f0b16" }, b = { fg = "#b2b8c1", bg = "#0f0b16" }, c = { fg = "#b2b8c1", bg = "#0f0b16" } },
}
