-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#ffffff", bg = "#01519f", gui = "bold" }, b = { fg = "#1b1d22", bg = "#f2f2f2" }, c = { fg = "#2e3036", bg = "#f7f7f7" } },
  insert = { a = { fg = "#ffffff", bg = "#056519", gui = "bold" }, b = { fg = "#1b1d22", bg = "#f2f2f2" }, c = { fg = "#2e3036", bg = "#f7f7f7" } },
  visual = { a = { fg = "#ffffff", bg = "#5634ac", gui = "bold" }, b = { fg = "#1b1d22", bg = "#f2f2f2" }, c = { fg = "#2e3036", bg = "#f7f7f7" } },
  replace = { a = { fg = "#ffffff", bg = "#9d0221", gui = "bold" }, b = { fg = "#1b1d22", bg = "#f2f2f2" }, c = { fg = "#2e3036", bg = "#f7f7f7" } },
  command = { a = { fg = "#ffffff", bg = "#694e05", gui = "bold" }, b = { fg = "#1b1d22", bg = "#f2f2f2" }, c = { fg = "#2e3036", bg = "#f7f7f7" } },
  inactive = { a = { fg = "#2e3036", bg = "#f7f7f7" }, b = { fg = "#2e3036", bg = "#f7f7f7" }, c = { fg = "#2e3036", bg = "#f7f7f7" } },
}
