-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#232336", bg = "#86bafe", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2d41" }, c = { fg = "#7c869c", bg = "#1d1d30" } },
  insert = { a = { fg = "#232336", bg = "#85cc87", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2d41" }, c = { fg = "#7c869c", bg = "#1d1d30" } },
  visual = { a = { fg = "#232336", bg = "#b6aaff", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2d41" }, c = { fg = "#7c869c", bg = "#1d1d30" } },
  replace = { a = { fg = "#232336", bg = "#fb9795", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2d41" }, c = { fg = "#7c869c", bg = "#1d1d30" } },
  command = { a = { fg = "#232336", bg = "#dbb155", gui = "bold" }, b = { fg = "#a0abc2", bg = "#2d2d41" }, c = { fg = "#7c869c", bg = "#1d1d30" } },
  inactive = { a = { fg = "#7c869c", bg = "#1d1d30" }, b = { fg = "#7c869c", bg = "#1d1d30" }, c = { fg = "#7c869c", bg = "#1d1d30" } },
}
