-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#24263a", bg = "#58c4fd", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e3045" }, c = { fg = "#828ca2", bg = "#1e2034" } },
  insert = { a = { fg = "#24263a", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e3045" }, c = { fg = "#828ca2", bg = "#1e2034" } },
  visual = { a = { fg = "#24263a", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e3045" }, c = { fg = "#828ca2", bg = "#1e2034" } },
  replace = { a = { fg = "#24263a", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e3045" }, c = { fg = "#828ca2", bg = "#1e2034" } },
  command = { a = { fg = "#24263a", bg = "#e7be62", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#2e3045" }, c = { fg = "#828ca2", bg = "#1e2034" } },
  inactive = { a = { fg = "#828ca2", bg = "#1e2034" }, b = { fg = "#828ca2", bg = "#1e2034" }, c = { fg = "#828ca2", bg = "#1e2034" } },
}
