-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#282134", bg = "#e990f6", gui = "bold" }, b = { fg = "#a0abc2", bg = "#322b3f" }, c = { fg = "#7c869c", bg = "#221b2e" } },
  insert = { a = { fg = "#282134", bg = "#85cc87", gui = "bold" }, b = { fg = "#a0abc2", bg = "#322b3f" }, c = { fg = "#7c869c", bg = "#221b2e" } },
  visual = { a = { fg = "#282134", bg = "#b6aaff", gui = "bold" }, b = { fg = "#a0abc2", bg = "#322b3f" }, c = { fg = "#7c869c", bg = "#221b2e" } },
  replace = { a = { fg = "#282134", bg = "#fb9795", gui = "bold" }, b = { fg = "#a0abc2", bg = "#322b3f" }, c = { fg = "#7c869c", bg = "#221b2e" } },
  command = { a = { fg = "#282134", bg = "#dbb155", gui = "bold" }, b = { fg = "#a0abc2", bg = "#322b3f" }, c = { fg = "#7c869c", bg = "#221b2e" } },
  inactive = { a = { fg = "#7c869c", bg = "#221b2e" }, b = { fg = "#7c869c", bg = "#221b2e" }, c = { fg = "#7c869c", bg = "#221b2e" } },
}
