-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#0e1019", bg = "#83b4f3", gui = "bold" }, b = { fg = "#8f98ab", bg = "#171923" }, c = { fg = "#6c7587", bg = "#090a14" } },
  insert = { a = { fg = "#0e1019", bg = "#86c387", gui = "bold" }, b = { fg = "#8f98ab", bg = "#171923" }, c = { fg = "#6c7587", bg = "#090a14" } },
  visual = { a = { fg = "#0e1019", bg = "#b0a6ef", gui = "bold" }, b = { fg = "#8f98ab", bg = "#171923" }, c = { fg = "#6c7587", bg = "#090a14" } },
  replace = { a = { fg = "#0e1019", bg = "#ec9693", gui = "bold" }, b = { fg = "#8f98ab", bg = "#171923" }, c = { fg = "#6c7587", bg = "#090a14" } },
  command = { a = { fg = "#0e1019", bg = "#d0ac5f", gui = "bold" }, b = { fg = "#8f98ab", bg = "#171923" }, c = { fg = "#6c7587", bg = "#090a14" } },
  inactive = { a = { fg = "#6c7587", bg = "#090a14" }, b = { fg = "#6c7587", bg = "#090a14" }, c = { fg = "#6c7587", bg = "#090a14" } },
}
