-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#272538", bg = "#fe9783", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f42" }, c = { fg = "#828ca2", bg = "#221f32" } },
  insert = { a = { fg = "#272538", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f42" }, c = { fg = "#828ca2", bg = "#221f32" } },
  visual = { a = { fg = "#272538", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f42" }, c = { fg = "#828ca2", bg = "#221f32" } },
  replace = { a = { fg = "#272538", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f42" }, c = { fg = "#828ca2", bg = "#221f32" } },
  command = { a = { fg = "#272538", bg = "#e7be62", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#312f42" }, c = { fg = "#828ca2", bg = "#221f32" } },
  inactive = { a = { fg = "#828ca2", bg = "#221f32" }, b = { fg = "#828ca2", bg = "#221f32" }, c = { fg = "#828ca2", bg = "#221f32" } },
}
