-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#2c2d36", bg = "#99c1f4", gui = "bold" }, b = { fg = "#98a2b5", bg = "#363740" }, c = { fg = "#757d90", bg = "#262730" } },
  insert = { a = { fg = "#2c2d36", bg = "#9ccd9c", gui = "bold" }, b = { fg = "#98a2b5", bg = "#363740" }, c = { fg = "#757d90", bg = "#262730" } },
  visual = { a = { fg = "#2c2d36", bg = "#bcb5f1", gui = "bold" }, b = { fg = "#98a2b5", bg = "#363740" }, c = { fg = "#757d90", bg = "#262730" } },
  replace = { a = { fg = "#2c2d36", bg = "#f0a8a5", gui = "bold" }, b = { fg = "#98a2b5", bg = "#363740" }, c = { fg = "#757d90", bg = "#262730" } },
  command = { a = { fg = "#2c2d36", bg = "#d7ba7d", gui = "bold" }, b = { fg = "#98a2b5", bg = "#363740" }, c = { fg = "#757d90", bg = "#262730" } },
  inactive = { a = { fg = "#757d90", bg = "#262730" }, b = { fg = "#757d90", bg = "#262730" }, c = { fg = "#757d90", bg = "#262730" } },
}
