-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#262e3e", bg = "#99c1f4", gui = "bold" }, b = { fg = "#98a2b5", bg = "#2f3849" }, c = { fg = "#757d90", bg = "#202838" } },
  insert = { a = { fg = "#262e3e", bg = "#9ccd9c", gui = "bold" }, b = { fg = "#98a2b5", bg = "#2f3849" }, c = { fg = "#757d90", bg = "#202838" } },
  visual = { a = { fg = "#262e3e", bg = "#bcb5f1", gui = "bold" }, b = { fg = "#98a2b5", bg = "#2f3849" }, c = { fg = "#757d90", bg = "#202838" } },
  replace = { a = { fg = "#262e3e", bg = "#f0a8a5", gui = "bold" }, b = { fg = "#98a2b5", bg = "#2f3849" }, c = { fg = "#757d90", bg = "#202838" } },
  command = { a = { fg = "#262e3e", bg = "#d7ba7d", gui = "bold" }, b = { fg = "#98a2b5", bg = "#2f3849" }, c = { fg = "#757d90", bg = "#202838" } },
  inactive = { a = { fg = "#757d90", bg = "#202838" }, b = { fg = "#757d90", bg = "#202838" }, c = { fg = "#757d90", bg = "#202838" } },
}
