-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#301e2c", bg = "#fe9783", gui = "bold" }, b = { fg = "#a0abc2", bg = "#3b2836" }, c = { fg = "#7c869c", bg = "#2a1926" } },
  insert = { a = { fg = "#301e2c", bg = "#85cc87", gui = "bold" }, b = { fg = "#a0abc2", bg = "#3b2836" }, c = { fg = "#7c869c", bg = "#2a1926" } },
  visual = { a = { fg = "#301e2c", bg = "#b6aaff", gui = "bold" }, b = { fg = "#a0abc2", bg = "#3b2836" }, c = { fg = "#7c869c", bg = "#2a1926" } },
  replace = { a = { fg = "#301e2c", bg = "#fb9795", gui = "bold" }, b = { fg = "#a0abc2", bg = "#3b2836" }, c = { fg = "#7c869c", bg = "#2a1926" } },
  command = { a = { fg = "#301e2c", bg = "#dbb155", gui = "bold" }, b = { fg = "#a0abc2", bg = "#3b2836" }, c = { fg = "#7c869c", bg = "#2a1926" } },
  inactive = { a = { fg = "#7c869c", bg = "#2a1926" }, b = { fg = "#7c869c", bg = "#2a1926" }, c = { fg = "#7c869c", bg = "#2a1926" } },
}
