-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#13131c", bg = "#f095ff", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1b1b21" }, c = { fg = "#b2b8c1", bg = "#0d0d12" } },
  insert = { a = { fg = "#13131c", bg = "#76e87d", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1b1b21" }, c = { fg = "#b2b8c1", bg = "#0d0d12" } },
  visual = { a = { fg = "#13131c", bg = "#b1b7fd", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1b1b21" }, c = { fg = "#b2b8c1", bg = "#0d0d12" } },
  replace = { a = { fg = "#13131c", bg = "#fe7f78", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1b1b21" }, c = { fg = "#b2b8c1", bg = "#0d0d12" } },
  command = { a = { fg = "#13131c", bg = "#f6d653", gui = "bold" }, b = { fg = "#cbd1da", bg = "#1b1b21" }, c = { fg = "#b2b8c1", bg = "#0d0d12" } },
  inactive = { a = { fg = "#b2b8c1", bg = "#0d0d12" }, b = { fg = "#b2b8c1", bg = "#0d0d12" }, c = { fg = "#b2b8c1", bg = "#0d0d12" } },
}
