-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#0c131d", bg = "#6bcafe", gui = "bold" }, b = { fg = "#cbd1da", bg = "#151c27" }, c = { fg = "#b2b8c1", bg = "#070d18" } },
  insert = { a = { fg = "#0c131d", bg = "#76e87d", gui = "bold" }, b = { fg = "#cbd1da", bg = "#151c27" }, c = { fg = "#b2b8c1", bg = "#070d18" } },
  visual = { a = { fg = "#0c131d", bg = "#b1b7fd", gui = "bold" }, b = { fg = "#cbd1da", bg = "#151c27" }, c = { fg = "#b2b8c1", bg = "#070d18" } },
  replace = { a = { fg = "#0c131d", bg = "#fe7f78", gui = "bold" }, b = { fg = "#cbd1da", bg = "#151c27" }, c = { fg = "#b2b8c1", bg = "#070d18" } },
  command = { a = { fg = "#0c131d", bg = "#f6d653", gui = "bold" }, b = { fg = "#cbd1da", bg = "#151c27" }, c = { fg = "#b2b8c1", bg = "#070d18" } },
  inactive = { a = { fg = "#b2b8c1", bg = "#070d18" }, b = { fg = "#b2b8c1", bg = "#070d18" }, c = { fg = "#b2b8c1", bg = "#070d18" } },
}
