-- generated by duskbox; do not edit by hand
return {
  normal = { a = { fg = "#1a2637", bg = "#58c4fd", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#233041" }, c = { fg = "#828ca2", bg = "#142030" } },
  insert = { a = { fg = "#1a2637", bg = "#89cc7b", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#233041" }, c = { fg = "#828ca2", bg = "#142030" } },
  visual = { a = { fg = "#1a2637", bg = "#b19ee3", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#233041" }, c = { fg = "#828ca2", bg = "#142030" } },
  replace = { a = { fg = "#1a2637", bg = "#f4514c", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#233041" }, c = { fg = "#828ca2", bg = "#142030" } },
  command = { a = { fg = "#1a2637", bg = "#e7c454", gui = "bold" }, b = { fg = "#a6b1c8", bg = "#233041" }, c = { fg = "#828ca2", bg = "#142030" } },
  inactive = { a = { fg = "#828ca2", bg = "#142030" }, b = { fg = "#828ca2", bg = "#142030" }, c = { fg = "#828ca2", bg = "#142030" } },
}
